### ISSUE TITLE
Default file menu

### ISSUE THREAD

**Issue by plaresmedima** [QIB-Sheffield/WEASEL#101]
We should take the File menu out of the configuration files. This should be a default menu with core functionality essential to weasel, and that is always there. 

If we keep it in config, weasel will not work properly if the user modifies it, so it should not be modifiable. Also, if we make a change (like we did with Open DICOM) then currently we have to copy-paste that change in all existing configurations, and ask all users to do the same for their external configurations. 

this is a v0.1 issue because once we roll it out it will be increasingly difficult to implement considering it requires changes in configuration files that are not in the weasel distribution.

**Comment by IMI-TRISTAN** [comment]
File menu now created in code.  Also, moved default file menu modules to CoreModules & added a Reset Tree View menu item that unchecks all checkboxes to the context menu and the File menu.   You will need remove the File section from you menu XML files.
