### ISSUE TITLE
Change code to include Subject level (subjectID)

### ISSUE THREAD

**Issue by JSousa-UoL** [QIB-Sheffield/WEASEL#15]
Until a couple of months ago, Weasel structure used to be Study-Series-Image. Now, a parent/root level named "Subject" was added recently in the XML, but no further changes were done at the time. Many functions of Weasel call and make use of studyID and seriesID. We need to update the project to include subjectID. I reviewed which files will be affected and I made a list below with a summary.

**Files to change to incorporate subjectID**

_Files related with visualisation:_
Weasel.py
DisplayImageColour.py
DisplayImageCommon.py
DisplayImageROI.py
LoadDICOM.py
ViewImage.py
ViewMetadata.py
ViewROIImage.py

_Files from algorithms/developer. These should be fairly easy to do:_
saveDICOM_Image (probably not, but keep it for consideration
BinaryOperationsOnImages.py
copyDICOM_Image.py
thresholdDICOM_Image.py
DeleteImage.py
ToolsFunctions.py

_Files involving TreeView and XML. These will probably involve more time and work:_
InterfaceDICOMXMLFile.py
TreeView.py
weaselXMLReader.py

**Comment by IMI-TRISTAN** [comment]
Have made the necessary changes in weaselXMLReader and in the image viewers.  After other areas have been tested, this issue can be closed.

**Comment by JSousa-UoL** [comment]
@IMI-TRISTAN , I made the corresponding changes on my side. I still will have a look at "BinaryOperationsOnImages.py".

I have one last request/favour in this - I noticed that there are global variables self.selectedStudy and self.selectedSeries which are used in the display titles. Would it be alright and easy enough to add self.selectedSubject and add it to the display title along with the study and series?

You can close this issue after this.

**Comment by IMI-TRISTAN** [comment]
That should be ok

**Comment by IMI-TRISTAN** [comment]
I've had a look at self.selectedStudy etc.  It looks like these are now
redundant since we started using checked images and series.  So I will look
at adding subject ID to the windows title in the same way that I do so for
study etc.

Regarding BinaryOperationsOnImages.py, it still uses the obsolete selected
series approach.  I need to convert this to using multiple checked series.

I'll try to do this, this evening
Steve

**Comment by JSousa-UoL** [comment]
Thank you so much for having a look at this this evening.

I have a request for the display windows titles after you add the subject part. Can you make the dashes consistent please? One of the titles concatenates " - " but the other concatenates "-". I need them to be consistent to resolve the closeWindow Delete issue.
