### ISSUE TITLE
Extra/Developer Python Installation Packages via XML file

### ISSUE THREAD

**Issue by JSousa-UoL** [QIB-Sheffield/WEASEL#22]
At the moment the main python packages are installed via setup.py.
However, a developer may wish to install other python packages (PyPi) that are not part of core Weasel.
One of the suggested solutions is for the developer to write the desired packages in the config.xml and Weasel.py ensures these are installed before running.

**Comment by plaresmedima** [comment]
Hi Joao,

I think the packages need to be written in the menu item somehow to keep
the modularity. Can weasel not run over all menu-items listed in the
current menu at startup, looking for packages that need to be installed?
Would it not be possible to identify missing packages from the import
statements at the top?

Prof. Steven Sourbron, PhD
Chair in Medical Imaging Physics
University of Sheffield, UK
*https
<https://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron>://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron
<https://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron>*
*Sheffield abdominal imaging research page*
<https://www.sheffield.ac.uk/medicine/research/research-themes/medical-imaging/medical-imaging-research/abdominal-imaging>
*Open source initiative in perfusion imaging* <http://www.osipi.org>
*Magnetic resonance imaging biomarkers for chronic kidney disease
<https://renalmri.org/>*

**Comment by JSousa-UoL** [comment]
_"Can weasel not run over all menu-items listed in the
current menu at startup, looking for packages that need to be installed?
Would it not be possible to identify missing packages from the import
statements at the top?"_
Not really, otherwise python would already do that by default. You can go through each individual import statement and do try/except but that's not practical at all

_"I think the packages need to be written in the menu item somehow to keep
the modularity"_
This is more plausible, if we have a leaf in the menu XML file called <packages>, then we could write there the list of packages.

Still, the most recommended alternative for both users and developers is by using setup.py and the way we have setup.py written is quite straightforward (https://stackoverflow.com/questions/6120902/how-do-i-automatically-install-missing-python-modules)

**Comment by JSousa-UoL** [comment]
Done in XNATapp.py and iBEATimport.py
