### ISSUE TITLE
Config 

### ISSUE THREAD

**Issue by plaresmedima** [QIB-Sheffield/WEASEL#26]
This line in config seems obsolete

<weasel_data_folder>\Weasel\WeaselData\SampleData</weasel_data_folder>

**Comment by JSousa-UoL** [comment]
You're right I can change that now to just \Weasel. Need to let @IMI-TRISTAN know because the file will be changed, which means he'll have to adapt his own config file to work on his machine

**Comment by JSousa-UoL** [comment]
I just committed a new version of config where the folder is just 'Weasel'. We can close this when @IMI-TRISTAN is aware of this change

**Comment by IMI-TRISTAN** [comment]
I've updated my config.xml and Weasel is working ok on my laptop
