### ISSUE TITLE
Visual studio files

### ISSUE THREAD

**Issue by plaresmedima** [QIB-Sheffield/WEASEL#27]
Weasled Python projects and visual studio files are still in main folder. 

Steven can you keep those locally?

**Comment by IMI-TRISTAN** [comment]
I have deleted the two Visual Studio files in the gitHub repository.  As they are in my gitignore file, they should not reappear in the Weasel repo' but I will monitor this

**Comment by plaresmedima** [comment]
Resolved by Steve
