### ISSUE TITLE
Application builder

### ISSUE THREAD

**Issue by plaresmedima** [QIB-Sheffield/WEASEL#38]
Procedure to compile configurations and build applications that can be distributed and run without accessing source code.

**Comment by JSousa-UoL** [comment]
@JSousa-UoL working on this

**Comment by JSousa-UoL** [comment]
We can distribute large executable/binary files with a release: https://docs.github.com/en/github/administering-a-repository/about-releases

**Comment by plaresmedima** [comment]
Yes but these are two different things I think? Not every executable needs
to be a formal release and you can also created formal releases of code
that is not an executable (like v0.1)

Prof. Steven Sourbron, PhD
Chair in Medical Imaging Physics
University of Sheffield, UK
*https
<https://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron>://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron
<https://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron>*
*Sheffield abdominal imaging research page*
<https://www.sheffield.ac.uk/medicine/research/research-themes/medical-imaging/medical-imaging-research/abdominal-imaging>
*Open source initiative in perfusion imaging* <http://www.osipi.org>
*Magnetic resonance imaging biomarkers for chronic kidney disease
<https://renalmri.org/>*

**Comment by JSousa-UoL** [comment]
They are different things and usually the formal releases are a zip file of the source code. However,
_Not every executable needs to be a formal release_ but every formal release *can* have an executable associated and the link explains how to do it. We should have a mechanism of creating an executable by using pyinstaller, but if we give a binary already in the release it'll be a lot more appealing/attractive to any user. And these binaries in the formal releases can go up to 2GB.

**Comment by plaresmedima** [comment]
sounds good - yes having some example executables in the distribution makes
sense

Prof. Steven Sourbron, PhD
Chair in Medical Imaging Physics
University of Sheffield, UK
*https
<https://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron>://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron
<https://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron>*
*Sheffield abdominal imaging research page*
<https://www.sheffield.ac.uk/medicine/research/research-themes/medical-imaging/medical-imaging-research/abdominal-imaging>
*Open source initiative in perfusion imaging* <http://www.osipi.org>
*Magnetic resonance imaging biomarkers for chronic kidney disease
<https://renalmri.org/>*

**Comment by JSousa-UoL** [comment]
`pyinstaller` and generating the executable is still working as expected after the changes in #36 and #89 - these issues could have posed very difficult compilation problems but that was not the case fortunately.

This issue should only be closed on the day of the release since we will make the executable available.
