### ISSUE TITLE
Pop up windows should not obscure TreeView

### ISSUE THREAD

**Issue by plaresmedima** [QIB-Sheffield/WEASEL#44]
We always need access to the TreeView so if a pop-up window pops over it then it has to be moved manually every time. Can we make sure the windows that pop up never overlap with the Tree View?

**Comment by IMI-TRISTAN** [comment]
This has been solved by displaying the tree view in a docked widget on the left-hand side of the screen.

**Comment by IMI-TRISTAN** [comment]
I've fixed this by displaying the tree view in a docked widget on the
left-hand side of the screen.  It's right-hand side edge can be dragged to
adjust it's width.  The image subwindows are displayed in the now smaller
MDI on the right-hand side but they can now be tiled using the Tile menu
command.  Please have a look and let me know what you think.
Steve

**Comment by IMI-TRISTAN** [comment]
Looks like this is working Steve! Nice.. Also the tiling of the subwindows
seems to be working.

Prof. Steven Sourbron, PhD
Chair in Medical Imaging Physics
University of Sheffield, UK
*https
<https://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron>://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron
<https://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron>*
*Sheffield abdominal imaging research page*
<https://www.sheffield.ac.uk/medicine/research/research-themes/medical-imaging/medical-imaging-research/abdominal-imaging>
*Open source initiative in perfusion imaging* <http://www.osipi.org>
*Magnetic resonance imaging biomarkers for chronic kidney disease
<https://renalmri.org/>*

**Comment by IMI-TRISTAN** [comment]
Great, thanks for letting me know.
