### ISSUE TITLE
Unexpected keyword argument

### ISSUE THREAD

**Issue by plaresmedima** [QIB-Sheffield/WEASEL#45]
line 282 in DeveloperTools.py calls displayImageSubWindow with a keyword argument but that does not exist.

displayImageColour.displayImageSubWindow(self.objWeasel, studyID, seriesID, derivedImagePath=inputPath)

**Comment by JSousa-UoL** [comment]
I'm adding Steve to the assignees. The new viewer compromises this part of the Developer tools it seems. It's also relating with the selection/checking problem

**Comment by JSousa-UoL** [comment]
I tested this and it's working ok. Should we close @IMI-TRISTAN ?

**Comment by IMI-TRISTAN** [comment]
yes, let's close it
