### ISSUE TITLE
Multiple Series view with two images only.

### ISSUE THREAD

**Issue by plaresmedima** [QIB-Sheffield/WEASEL#46]
If I display a series of two images (or a list of two images), the slider at the bottom does not move unless I click beyond the middle. Took me a while to realise that. I though it was not displaying the second image.

Generally the slider seems a little erratic when I have only a few images open. I tried it with 4 and it jumps from left to right in a sometimes unpredictable way.

**Comment by IMI-TRISTAN** [comment]
the width of the slider is set according to the number of images in the series.
