### ISSUE TITLE
Image.new() bug in DeveloperTools

### ISSUE THREAD

**Issue by plaresmedima** [QIB-Sheffield/WEASEL#49]
Line 1031 and 1032 in DeveloperTools.py

            newImage = Image(series.objWeasel, series.subjectID, series.studyID, series.seriesID, '', suffix=suffix)
            newImage.parent = series

Generates an error because objects of class "Image" do not have a parent attribute.

This came up in Template_InvertPixelValuesNew.py, line 13

**Comment by JSousa-UoL** [comment]
This should be resolved in the new commit. Please have a look to see if the same error happens.
