### ISSUE TITLE
Exit button of some apps (XNAT, Gaussian, etc.) doesn't work correctly in Mac OS

### ISSUE THREAD

**Issue by JSousa-UoL** [QIB-Sheffield/WEASEL#50]
@KanishkaS ' comment:

@JSousa-UoL: The exit button ('red cross') still has the issue. I did not attempt to login but only exited using this option rather than cancel and it throws the following error.

[CRITICAL] Login attempt failed for https://xnat.vital-it.ch, please make sure your credentials for user  are correct!
Traceback (most recent call last):
  File "/Users/kanishkasharma/Documents/GitHub/WEASEL/CoreModules/WEASEL/Menus.py", line 62, in <lambda>
    self.menuItem.triggered.connect(lambda : objFunction(self))
  File "/Users/kanishkasharma/Documents/GitHub/WEASEL/Pipelines/iBEAt/XNATappiBEAt.py", line 22, in download
    with xnat.connect(url, user=username, password=password) as session:
  File "/Users/kanishkasharma/.local/lib/python3.8/site-packages/xnat/__init__.py", line 402, in connect
    logged_in_user = check_auth(requests_session, server=server, user=user, logger=logger)
  File "/Users/kanishkasharma/.local/lib/python3.8/site-packages/xnat/__init__.py", line 66, in check_auth
    raise exceptions.XNATLoginFailedError(message)
xnat.exceptions.XNATLoginFailedError: Login attempt failed for https://xnat.vital-it.ch, please make sure your credentials for user  are correct!
Abort trap: 6

**Comment by JSousa-UoL** [comment]
This specific window close button issue seems to be Mac-only. This exit ('red cross') button is disabled in Windows but it seems that for Mac it's active and the action triggered is the same as the OK button.
Unfortunately this cannot be solved now as we're developing Weasel for Weasel. You'll have to use the cancel button in every Weasel application and please avoid the exit button in Mac for now. It seems this isn't only on XNAT application, it also happens on Pipelines' applications such as Threshold, Square, etc.
I'm going to close this issue and open a new one with these last two comments.

**Comment by JSousa-UoL** [comment]
@KanishkaS I made a new commit when this was resolved. This change means that for input windows for Gaussian, Threshold and XNAT, the close button should be either hidden or disabled.
I tested on my Mac VM, but could you try this on yours to check if it's working? Feel free to close if it's all good.

**Comment by KanishkaS** [comment]
@JSousa-UoL: the button is disabled now but the pop-up window looks strange (see - 'ok' and 'cancel' button). Not sure if this is again a resolution issue. 
![Screenshot 2021-02-25 at 10 56 26](https://user-images.githubusercontent.com/42036722/109107736-46961380-7758-11eb-887a-aa14d40e9e5c.png)

**Comment by JSousa-UoL** [comment]
It is related to the resolution issue - linking #55

**Comment by JSousa-UoL** [comment]
Solution in #55
