### ISSUE TITLE
Slider to view images

### ISSUE THREAD

**Issue by KanishkaS** [QIB-Sheffield/WEASEL#52]
The GUI slider to view different slices does not function with keyboard strokes (or the shortcut is not intuitive if it is present). Only with manual slider shifting. It may be more convenient to add keyboard option as well - particularly useful when working with large number of slices as it is difficult to use the slider in that case.

**Comment by JSousa-UoL** [comment]
This is another Mac OS related issue. I need to see if I can create a label for Mac related issues. This works for Windows and I just tried on my Mac VM and indeed you can't use the arrow keys to scroll across slices. I'm afraid you will encounter several issues like this in the next days and weeks

**Comment by JSousa-UoL** [comment]
@KanishkaS I made a new commit when this was resolved. I tested on my Mac VM, but could you try this on yours to check if it's working. Feel free to close if it's all good.

**Comment by KanishkaS** [comment]
thanks @JSousa-UoL: it works now!
