### ISSUE TITLE
sort does not identify some tags - seriesMagnitude.sort

### ISSUE THREAD

**Issue by KanishkaS** [QIB-Sheffield/WEASEL#54]
sort function does not sort slices based on selected criteria - eg: echo times, etc.

**Comment by KanishkaS** [comment]
Update: The sorting is working for T2*mapping now with different TEs but there is still an issue for sorting tags such as 'PrepTime' which might be hidden in other DICOM tags.

**Comment by JSousa-UoL** [comment]
Is PrepTime AcquisitionTime? What tag is it? You can technically access via DICOM tag - this is also something that I need to improve a bit as I don't have many example use cases.

**Comment by KanishkaS** [comment]
This is equivalent to inversion time for T1 or Echo time for T2* sequence. In matlab, it is found in the 'imageComments' tag of the dicom header. I could not locate it in IDL or by manually browsing the dicom header, so it is probably hidden.

**Comment by JSousa-UoL** [comment]
Ok, we can have a look tomorrow. I think the best is to start with a
case-by-case approach

**Comment by KanishkaS** [comment]
Update: The matlab tag for T2 PrepTime on Siemens scans previously accessed from 'Image comments' (matlab: strsplit(info.ImageComments) is removed after anonymisation on the scanner. This tag most likely needs to be added manually.

**Comment by JSousa-UoL** [comment]
I see, that's a bit tricky. I will share here the site I showed you earlier: https://dicom.innolitics.com/ciods/mr-image

It's a nice DICOM tags browser and you may be able to find the PrepTime in another DICOM tag that you're not expecting.

**Comment by JSousa-UoL** [comment]
I'm closing this issue after a meeting between myself and Kanishka 2 weeks ago resulted in some clarification. It's possible that there might be issues with the sort function, as it wasn't frequently tested yet.

**Comment by plaresmedima** [comment]
I will look at sort. It's tricky to get right but there are many functions
available that we can use as well.

Prof. Steven Sourbron, PhD
Chair in Medical Imaging Physics
University of Sheffield, UK
*https
<https://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron>://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron
<https://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron>*
*Sheffield abdominal imaging research page*
<https://www.sheffield.ac.uk/medicine/research/research-themes/medical-imaging/medical-imaging-research/abdominal-imaging>
*Open source initiative in perfusion imaging* <http://www.osipi.org>
*Magnetic resonance imaging biomarkers for chronic kidney disease
<https://renalmri.org/>*
