### ISSUE TITLE
Unable to expand view for DICOM image/series

### ISSUE THREAD

**Issue by KanishkaS** [QIB-Sheffield/WEASEL#55]
The DICOM series/image pops up in a small window which cannot be expanded easily - needs to be dragged manually. Would be ideal to double click on series to expand view in a simple manner.

![Screenshot 2021-02-18 at 15 13 33](https://user-images.githubusercontent.com/42036722/108338433-421fa700-71fc-11eb-8129-fd81c7153bc6.png)

**Comment by JSousa-UoL** [comment]
I removed the MacOS label as this isn't operative system related. In lower resolution monitors this works alright, but I tried this in a Windows with a resolution of 1920x1080 pixels and this same issue occurred. I can use the mouse to adjust the width of the Treeview. but in this resolution I cannot shrink beyond this width in the screenshot.
Are you ok to have a look at this @IMI-TRISTAN? Issue #64 is also related with the TreeView graphics.

**Comment by JSousa-UoL** [comment]
I found a potential solution to this which I will try later => it will involve files "Weasel.py" and "TreeView.py".
"Weasel.py" - the following lines should be added after the imports. It resolves the high-resolution monitors issue.
`
if hasattr(Qt, 'AA_EnableHighDpiScaling'):
    QApplication.setAttribute(Qt.AA_EnableHighDpiScaling, True)

if hasattr(Qt, 'AA_UseHighDpiPixmaps'):
    QApplication.setAttribute(Qt.AA_UseHighDpiPixmaps, True)
`

"TreeView.py" - with this resolution solved, TreeView width becomes very large, so:
`self.treeView.setMinimumSize(700,500)` should become `self.treeView.setMinimumSize(300,500)`

**Comment by JSousa-UoL** [comment]
The comment above is the right solution. Will close this when implemented (waiting for other changes).

**Comment by JSousa-UoL** [comment]
Hi @KanishkaS , this should be resolved now hopefully. Please have a quick look and let me know if it's all good.

**Comment by KanishkaS** [comment]
@JSousa-UoL : yes, I can expand it on manual drag. It doesn't work yet on double clicking the series which may also be ideal for users.

**Comment by JSousa-UoL** [comment]
Great news! That's right, we made significant changes to the TreeView and there's still a lot to be corrected. especially the columns. I'll close this issue and I'm sure more will be raised in a future round of tests.
