### ISSUE TITLE
Single new Series shows up as two series in Treeview

### ISSUE THREAD

**Issue by plaresmedima** [QIB-Sheffield/WEASEL#56]
@JSousa-UoL please run this pipeline to see the issue

Tutorial_InvertPixelValuesInNewSeries.py 

Do this: check two images from two different series and run the pipeline. It will work but the Treeview will show the results in two different series. The intention is that they both end up in the same series and that is also what is done in the code: I only generate one new Series and then save each new image in that one new series. So why does the TreeView show 2 new Series?

**Comment by JSousa-UoL** [comment]
First change for you to do is the following:
"
    def NewParent(self, suffix="_Suffix"):
        """
        Creates a new parent series from the images in the list.
        """
        return Image.newSeriesFrom(self.List, suffix=suffix)
"
Basically the return should start with Image. and not self.List[0]. However, the problem will still exist and I'll write another comment. I recommend that you keep progressing on your work as I might take days to solve this.

**Comment by JSousa-UoL** [comment]
This isn't a new problem, I came across  this before when writing the merge function, but still it doesn't seem to be solved yet.
![Capture](https://user-images.githubusercontent.com/53518061/108359021-5907ce80-71e7-11eb-8ece-d6d410fe16c5.PNG)
This is an issue either in the refresh function or in the InterfaceXML.py file (I'm almost sure it's this one). Basically, the DICOM files are saved correctly but the information in the XML/Treeview isn't recorded correctly after the operation. If you re-generate the XML file, it will be correct.
![Capture2](https://user-images.githubusercontent.com/53518061/108359206-9b311000-71e7-11eb-97e7-97256f313d86.PNG)

**Comment by plaresmedima** [comment]
self.List[0] is an object of class Image so both solutions should be the
same. I prefer self.List[0] because it makes it explicit that you don't
need to import another module to run this method.

Prof. Steven Sourbron, PhD
Chair in Medical Imaging Physics
University of Sheffield, UK
*https
<https://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron>://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron
<https://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron>*
*Sheffield abdominal imaging research page*
<https://www.sheffield.ac.uk/medicine/research/research-themes/medical-imaging/medical-imaging-research/abdominal-imaging>
*Open source initiative in perfusion imaging* <http://www.osipi.org>
*Magnetic resonance imaging biomarkers for chronic kidney disease
<https://renalmri.org/>*

**Comment by JSousa-UoL** [comment]
That's correct

**Comment by plaresmedima** [comment]
Regarding the main issue of the two images showing up in separate series: I tried reloading the DICOM data folder as you suggested but this does not solve the problem. They are still in two different series. In addition, they are now the same. 

So this is the sequence of events:

1) check images A in series SA and image B series SB
2) Apply Tutorial_InvertPixelValuesInNewSeries
3) Now you find the inverse of image A in a new series X and the inverse of image **B** in a new series Y
4) Reload the DICOM images
5) Now you find the inverse of image A in series X and the inverse of image **A** in series Y

**Comment by JSousa-UoL** [comment]
That's strange, the regeneration of the XML issue is not happening to me. The sequence of events only happens to me when I perform the algorithm and it happens as you describe.
This is going to be a challenge, I thought I had this issue resolved a long time ago. So let me get this straight:
- The objective is to perform the inversion on Series A and B and save them into a series X?

**Comment by JSousa-UoL** [comment]
I'm understanding the problem a bit better: Right now, it's writing the PixelArray to the new series in the first iteration, but then it tries to overwrite the series in a second iteration. That's why it's important to know if we want A and B to result in X and Y or for A and be to result in X only.

**Comment by plaresmedima** [comment]
In this case A and B should both end up in the same series X. Only one new
series is created in the pipeline. If I wanted A and B in two different
series then I would first create two new series and then save A in the
first and B in the second.

**Comment by JSousa-UoL** [comment]
@plaresmedima, I found the cause of this issue. This is happening because although everything is being saved into 1 series, the images that are part of it come from 2 different series which result in 2 different <parentID=> tags in the XML file. As a consequence, the Treeview presents it as 2 different series sharing the exact same name and ID, but having a different parentID which we cannot see unless we open the file.

I sent an email to @IMI-TRISTAN about this. The easy solution would be to remove this parentID from the XML. The reality is that this parentID is created when saving DICOM files into a new series, but it's not being used in anything so it's actually irrelevant and that's what's causing this problem.

**Comment by plaresmedima** [comment]
Great, that sounds like a good solution!
