### ISSUE TITLE
Tutorials for Website

### ISSUE THREAD

**Issue by JSousa-UoL** [QIB-Sheffield/WEASEL#57]
nbinteract seems to be an interesting package to look at: 
https://www.nbinteract.com/tutorial/tutorial_interact.html
https://www.youtube.com/watch?v=jln6h-dE2-0
https://elc.github.io/posts/embed-interactive-notebooks/

Creating blocks of code for the website is an easy task but making an interactive notebook with Weasel will be a bit of a challenge and time consuming. First, the notebook and DICOM data would have to be in weasel-web repository, which is ok. The problem is how we would call Weasel functions and packages from a non-Weasel repository. Would we have to run installation steps every time? This is what needs to be investigated when time allows.

**Comment by JSousa-UoL** [comment]
Interaction may be a difficult challenge. An easier and probably better looking approach is to write a Jupyter Notebook with the Developer code blocks and following each block we display a GIF where we see the outcome in the GUI. Then the .ipynb would be converted to html.
https://towardsdatascience.com/make-your-data-models-into-websites-d7260956c6d7

**Comment by plaresmedima** [comment]
Looks good. I will get started using the mark up method we already have and
then we look at these other options later.

**Comment by JSousa-UoL** [comment]
Google Colab also seems an interesting choice, but we still are probably going to use GIFs to explain and show outputs
