### ISSUE TITLE
Error in function #.displayImages: cannot unpack non-iterable NoneType object

### ISSUE THREAD

**Issue by plaresmedima** [QIB-Sheffield/WEASEL#58]
The bug happens in Tutorial_InvertPixelValuesSeriesInNewSeries

This works:

![image](https://user-images.githubusercontent.com/6051075/108431391-b4af7780-723a-11eb-9216-7c677dc6caa1.png)

But I want to display every series that is created, not just the last one. So I want to pull the Display() into the loop

![image](https://user-images.githubusercontent.com/6051075/108431469-d0b31900-723a-11eb-9310-93a5e1e75d77.png)

This is when I get the error. It doesn't always happen for some reason, just sometimes - I haven't found the pattern of when it happens and when not

**Comment by JSousa-UoL** [comment]
I managed to identify the source of this issue. Every time .write() is used, the XML file is updated, but not the Treeview. The Treeview is updated with Weasel.Refresh. The Display() function works based on the Treeview.
So, in order for that code to work, you would have to run Weasel.Refresh before the Display() every loop - which isn't really convenient to be honest.
For now, Weasel.Refresh and then newSeries.Display() will work fine and quickly in small datasets.
As part of the solution for this issue I have to think of a way to perform a fast and easy Refresh of the TreeView when using the .write() command.

**Comment by plaresmedima** [comment]
Can you not rewrite Display() so it does not use the TreeView? If we want
to refresh the TreeView during a loop we can always move Weasel.Refresh()
inside the loop. But in most conditions that will not be needed and will
slow down the calculations unnecessarily.

**Comment by JSousa-UoL** [comment]
That's another option I will explore but I have my doubts because Display() is written based on the display CoreModule which uses/reads the Treeview. But again, I will explore your suggestion as an alternative.

**Comment by JSousa-UoL** [comment]
This is resolved now. I'll leave it toThis is resolved now. I'll leave it to you to test it first @plaresmedima and then you may close this issue. you to test it first @plaresmedima and then you may close this issue.

**Comment by plaresmedima** [comment]
It seems to work now but it has created another bug. I will close this
issue and make a new issue for the bug

Prof. Steven Sourbron, PhD
Chair in Medical Imaging Physics
University of Sheffield, UK
*https
<https://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron>://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron
<https://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron>*
*Sheffield abdominal imaging research page*
<https://www.sheffield.ac.uk/medicine/research/research-themes/medical-imaging/medical-imaging-research/abdominal-imaging>
*Open source initiative in perfusion imaging* <http://www.osipi.org>
*Magnetic resonance imaging biomarkers for chronic kidney disease
<https://renalmri.org/>*
