### ISSUE TITLE
Deleting all images in a series does not delete the series

### ISSUE THREAD

**Issue by plaresmedima** [QIB-Sheffield/WEASEL#62]
I selected all images in a series, the applied Tutorial_Delete.py. This deletes the source data (no image displayed) but does not remove the series from the TreeView. Reloading does not solve the problem. I'm pretty sure I have tried this and this worked before so seems to be some issue that was introduced recently.

![image](https://user-images.githubusercontent.com/6051075/108640909-4f56c300-7494-11eb-88f3-19f02e652663.png)

**Comment by JSousa-UoL** [comment]
Please hold this copy and delete tutorials, I didn't know you were advancing to these already. The generic DICOM tools for merge, copy and delete were created before the DeveloperModule, but only merge was included in the classes Image() and Series(). I still need to create a function called .copy(suffix="_Copy") and .delete(). Once these are done, you can call them directly from Scripting.py. For now, leave this to me and I'll let you know once I made progress.
