### ISSUE TITLE
Copy Images saves copies in new series

### ISSUE THREAD

**Issue by plaresmedima** [QIB-Sheffield/WEASEL#63]
When I apply Tutorial_CopyImages.py the copies are saved in a new series. The intention is that they are saved in the same series.

The new copy is created via

Copy = self.new(suffix="_Copy")

and this should save the copy in the same series

    def new(self, suffix='_Copy', series=None):
        if series is None:
            newImage = Image(self.objWeasel, self.subjectID, self.studyID, self.seriesID, '', suffix=suffix)

**Comment by JSousa-UoL** [comment]
Please hold this copy and delete tutorials, I didn't know you were advancing to these already. The generic DICOM tools for merge, copy and delete were created before the DeveloperModule, but only merge was included in the classes Image() and Series(). I still need to create a function called .copy(suffix="_Copy") and .delete(). Once these are done, you can call them directly from Scripting.py. For now, leave this to me and I'll let you know once I made progress.

**Comment by plaresmedima** [comment]
OK I will pause - this functionality for copying, deleting, merging, etc at
image/series/study/subject level is the basis of everything else so needs
to be done before we can look at building image processing pipelines.

Prof. Steven Sourbron, PhD
Chair in Medical Imaging Physics
University of Sheffield, UK
*https
<https://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron>://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron
<https://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron>*
*Sheffield abdominal imaging research page*
<https://www.sheffield.ac.uk/medicine/research/research-themes/medical-imaging/medical-imaging-research/abdominal-imaging>
*Open source initiative in perfusion imaging* <http://www.osipi.org>
*Magnetic resonance imaging biomarkers for chronic kidney disease
<https://renalmri.org/>*

**Comment by JSousa-UoL** [comment]
This should be resolved in the new commit.
