### ISSUE TITLE
TreeView refresh - column width reset

### ISSUE THREAD

**Issue by plaresmedima** [QIB-Sheffield/WEASEL#64]
When the TreeView refereshes the widthd of the columns Dicom Files, Date, Time, should stay the same

**Comment by IMI-TRISTAN** [comment]
Made code changes but unable to test as there is a bug in the pipeline menu invert function

**Comment by plaresmedima** [comment]
Thanks I am changing some of the notations - should be working now but I
have not tested properly yet

Prof. Steven Sourbron, PhD
Chair in Medical Imaging Physics
University of Sheffield, UK
*https
<https://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron>://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron
<https://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron>*
*Sheffield abdominal imaging research page*
<https://www.sheffield.ac.uk/medicine/research/research-themes/medical-imaging/medical-imaging-research/abdominal-imaging>
*Open source initiative in perfusion imaging* <http://www.osipi.org>
*Magnetic resonance imaging biomarkers for chronic kidney disease
<https://renalmri.org/>*

**Comment by IMI-TRISTAN** [comment]
I loaded dicom data into the tree view and adjusted the columns. They remained the same after a tree view refresh
