### ISSUE TITLE
series numbers: incrementing with 1

### ISSUE THREAD

**Issue by plaresmedima** [QIB-Sheffield/WEASEL#65]
I invert a series called

17_*fl2d1

The result is called

17503_*fl2d1_Invert

This should just be

17_*fl2d1_Invert

**Comment by JSousa-UoL** [comment]
I believe we've discussed about this in the past. Every script in "Tools" creates a new series/image. When you create a new series, you have to create a new seriesID, you cannot use the same seriesID - that goes against DICOM rules and XNAT wouldn't accept that series in an upload. Now, if the idea is to overwrite DICOM data, then the invert scripts you've been writing should be able to do what you're suggesting.

**Comment by plaresmedima** [comment]
Solution: When a new series is created, find the largest series number we already have in the same study, then add 1, this is the series number of the new series

**Comment by JSousa-UoL** [comment]
Please test this when possible @plaresmedima. This is in the new commit and I made quite some testing, but I think it still needs more.
