### ISSUE TITLE
Series.merge() - take out refresh?

### ISSUE THREAD

**Issue by plaresmedima** [QIB-Sheffield/WEASEL#68]
@JSousa-UoL can we take out the line that refreshes weasel? A refresh is always done explicitly in any pipeline anyway so no need to do it in intermediate calculations. I think in general for modularity of the code it helps to keep file management from GUI management separate. Without the user interface command this merge function just becomes another DICOM tool. 

  @staticmethod
    def merge(listSeries, series_id=None, series_name='NewSeries', series_uid=None, suffix='_Merged', overwrite=False):
        outputSeries = listSeries[0].new(suffix=suffix, series_id=series_id, series_name=series_name, series_uid=series_uid)
        pathsList = [image for series in listSeries for image in series.images]
        outputPathList = GenericDICOMTools.mergeDicomIntoOneSeries(outputSeries.objWeasel, pathsList, series_uid=series_uid, series_id=series_id, series_name=series_name, suffix=suffix, overwrite=overwrite)
        UserInterfaceTools(listSeries[0].objWeasel).refreshWeasel(new_series_name=listSeries[0].seriesID)
        outputSeries.images = outputPathList
        outputSeries.referencePathsList = outputPathList
        return outputSeries

And then the same thing in the merge method for the Image class

**Comment by JSousa-UoL** [comment]
The TreeView needs to be updated, so the RefreshWeasel is vital for the merge to succeed. This is something I tried to remove before when I developed it for the first time, but we really need the Refresh there, I cannot remove it. I'm linking this issue to #56 and #59 as they all have "improving refresh / treeview update" as a resulting task. It's clear that the Treeview update needs another approach and this was something considered at the time when the merge algorithm was developed.

**Comment by JSousa-UoL** [comment]
In the beginning, I had the RefreshWeasel done explicitly in the pipeline, but because I thought the developer wouldn't do it everytime it merged I decided to move into the function merge. So, you just wish for that line to be removed?

**Comment by plaresmedima** [comment]
Yes please, just that line - same in image.

We for now we can leave it as a responsability for the pipeline developer
to insert the refresh statement at the end. It may be so that every
pipeline will end with Weasel.Refresh() in which case we can always
automate that.

Prof. Steven Sourbron, PhD
Chair in Medical Imaging Physics
University of Sheffield, UK
*https
<https://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron>://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron
<https://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron>*
*Sheffield abdominal imaging research page*
<https://www.sheffield.ac.uk/medicine/research/research-themes/medical-imaging/medical-imaging-research/abdominal-imaging>
*Open source initiative in perfusion imaging* <http://www.osipi.org>
*Magnetic resonance imaging biomarkers for chronic kidney disease
<https://renalmri.org/>*
