### ISSUE TITLE
Load DICOM images - logic

### ISSUE THREAD

**Issue by plaresmedima** [QIB-Sheffield/WEASEL#73]
The question ".. Would you like to load it?" is still confusing. I click no and then it is doing something anyway. 

I would like to do it like this:

-> Rename "Load DICOM images" to "Open DICOM folder"
-> It does this: In an XML already exists, just open it. If no XML exists, create one first and then open it. Do not ask the user anything.

Then:
-> Create a second menu item called "Refresh DICOM folder"
-> It does this: create a new XML (even if one exists already) and open it. 

I think we also need a menu item called "Close DICOM folder". This also writes the XML to disk.

**Comment by IMI-TRISTAN** [comment]
I am currently working on this issue.

**Comment by IMI-TRISTAN** [comment]
Created the three File menu items mentioned above

**Comment by plaresmedima** [comment]
Reopened this as there are a few issues left.

**1** Upon clicking "refresh DICOM" do not ask the user to select a directory again. This should just recreate the same XML for the same directory. Refresh should be unclickable when no DICOM folder is open. 

**2** I get some error reports as I open, close, refresh

Error in WriteXMLfromDICOM.get_study_series: 'FileDataset' object has no attribute 'SeriesDescription'
Error in WriteXMLfromDICOM.build_dictionary: cannot unpack non-iterable NoneType object
Error in WriteXMLfromDICOM.open_dicom_to_xml: 'NoneType' object is not iterable
Error in WriteXMLfromDICOM.create_XML_file: 'NoneType' object has no attribute 'iter'
XML file creation time = 9.939924478530884
Error in TreeView.makeDICOMStudiesTreeView at line 141: stat: path should be string, bytes, os.PathLike or integer, not NoneType
XML file creation time = 2.408388376235962
Error in WeaselXMLReader.setSeriesExpandedState: 'NoneType' object has no attribute 'set'

**Comment by JSousa-UoL** [comment]
1 issue reported on the 23rd March:
- When user presses "Close DICOM Folder", the "Refresh DICOM Folder" and "Close DICOM Folder" button should be greyed out
