### ISSUE TITLE
tile subwindows greyed out

### ISSUE THREAD

**Issue by plaresmedima** [QIB-Sheffield/WEASEL#76]
I have multiple images on display but the Tile Subwindows button is greyed out.

Seems to be because everything is greyed out unless I have something checked. Tile Subwindows and functions like Load DICOM should never be greyed out

**Comment by IMI-TRISTAN** [comment]
Unchecking all checkboxes should disable all the Tools menu items.  Unfortunately, this logic was being applied to the File menu. Now the File menu is excluded from this.
