### ISSUE TITLE
TreeView refresh causes collapse

### ISSUE THREAD

**Issue by plaresmedima** [QIB-Sheffield/WEASEL#78]
If I refresh the treeview then it collapses all series. So if I am working on the images in a series I have lost track of where I was working.

Also it always jumps back to the top of the treeview after a refresh so I have to scroll down to where I was after each operation.

Can the state of the treeview be stored so that it can be recovered after a refresh?

**Comment by IMI-TRISTAN** [comment]
It should be possible to save information about the series and the image being worked on and after a tree view refresh reload these.  Can you tell me how to create a scenario where this would need to be done

**Comment by JSousa-UoL** [comment]
Add line of code, wherever you add a new branch to the xml file.  It only needs doing for subjects, studies and series. Not images.
`subject_element.set('expanded', 'False')`

**Comment by IMI-TRISTAN** [comment]
I've completed and committed a fix to the collapse of the tree view when it
is refreshed.  I've tested it when copying series and works ok here.
Please test it with other functionality when you have time and close the
issue if everything is working properly.
Steve

**Comment by IMI-TRISTAN** [comment]
Now persisting checked state between refreshes.  Checked state stored as in an attribute in the DICOM xml file.  It is also saved to disc and picked up the next time file is loaded. But the same is not done with expanded state because the tree view branches have to be collapsed to set column widths.

**Comment by plaresmedima** [comment]
Thanks Steve - that will be very useful to preserve the checked state.

One question - let's say I check a single image inside a series, then close
the project and later reopen it again. This seried will not be expanded if
I understand correctly? So it could be that I have hidden checked images
inside series that are collapsed? If that is the case this could be
dangerous as any operation I do will then also act on those even if it is
not apparent to me that they are checked.

**Comment by IMI-TRISTAN** [comment]
That is correct.  If we wish to maintain checked items from a previous
session then I could add a function to expand tree view branches from the
previous session.  But when the tree view is big, then you have to scroll
down to see checked items at the bottom of it.  So the same problem may
arise, performing an unintentional operation on an unseen checked item.  So
perhaps the best course of action would be to set all checked and expanded
attributes in the xml file to False, when the tree view is loaded at the
start of a session.

**Comment by plaresmedima** [comment]
How about we have a default action that series are automatically expanded
as soon as there is at least one image checked?

I think if we have that in place then it is less critical to preserve the
expanded state. I think it's Ok that a series with no checked images
automatically collapses after a refresh for instance.

It's the user's responsibility to make sure they have the correct items
checked before they apply an operation, even if things are checked further
down. It's just that if we hide what is checked then it is very difficult
for them to verify that.

Prof. Steven Sourbron, PhD
Chair in Medical Imaging Physics
University of Sheffield, UK
*https
<https://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron>://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron
<https://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron>*
*Sheffield abdominal imaging research page*
<https://www.sheffield.ac.uk/medicine/research/research-themes/medical-imaging/medical-imaging-research/abdominal-imaging>
*Open source initiative in perfusion imaging* <http://www.osipi.org>
*Magnetic resonance imaging biomarkers for chronic kidney disease
<https://renalmri.org/>*

**Comment by IMI-TRISTAN** [comment]
"How about we have a default action that series are automatically expanded
as soon as there is at least one image checked?" might be complicated to
implement and test.  I suggest we go with the simpler, remove all previous
state when an existing DICOM xml file is reloaded in a new session. From a
coding perspective, it is a cleaner solution and the user will know where
they stand.  For example, what if a user loads an XML file they have not
used for a week?  I cannot remember what I did yesterday! so they may have
no idea what was checked or expanded from last time.  Or what if several
users use the same file?  I know this is unlikely at the moment, but when
users use the same data on a shared drive it may become an issue.

**Comment by IMI-TRISTAN** [comment]
Please test that tree view state is being saved and cleared as expected.
