### ISSUE TITLE
merging images does not do anything

### ISSUE THREAD

**Issue by plaresmedima** [QIB-Sheffield/WEASEL#79]
Tutorial_MergeImages.py

Nothing happens if I click it

**Comment by JSousa-UoL** [comment]
This is because the return statement is exiting before the merge method. You'll have to change ".empty" to ".empty()" and then this problem will be solved @plaresmedima

**Comment by plaresmedima** [comment]
Thanks @JSousa-UoL

**Comment by plaresmedima** [comment]
Ok - thanks! My bad..

Prof. Steven Sourbron, PhD
Chair in Medical Imaging Physics
University of Sheffield, UK
*https
<https://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron>://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron
<https://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron>*
*Sheffield abdominal imaging research page*
<https://www.sheffield.ac.uk/medicine/research/research-themes/medical-imaging/medical-imaging-research/abdominal-imaging>
*Open source initiative in perfusion imaging* <http://www.osipi.org>
*Magnetic resonance imaging biomarkers for chronic kidney disease
<https://renalmri.org/>*
