### ISSUE TITLE
DeleteSeries does not delete all images

### ISSUE THREAD

**Issue by plaresmedima** [QIB-Sheffield/WEASEL#84]
It seems that series.delete() deletes all the images in a series except the last one.

The screenshot below shows the result of deleting the last series in the study

![image](https://user-images.githubusercontent.com/6051075/110254459-1d128e80-7f87-11eb-85b3-4c9eb23120e5.png)

**Comment by plaresmedima** [comment]
This might be a problem in copy becasue the image is invalid

Error in function readDICOM_Image.getColourmap: 'NoneType' object has no attribute 'dir'
Error in DisplayImageColour.displayImageSubWindow: cannot unpack non-iterable NoneType object

**Comment by JSousa-UoL** [comment]
We should close this issue. The issue in this case is already raised in #77 (they're the same)
