### ISSUE TITLE
Rewrite weasel.user_input()

### ISSUE THREAD

**Issue by plaresmedima** [QIB-Sheffield/WEASEL#85]
Rewrite the wrapper user_input() like this (pseudo-code)

    cancel, width, A, B, operation = weasel.user_input(title="Settings for binary operation", 
        {"type":"float", "label":"Filter width in pixels", "default":1.0}
        {"type":"list", "label":"Image A", "default":0,  "list": Images(0x0018, 0x0024)}
        {"type":"list", "label":"Image B", "default":0,  "list": Images(0x0018, 0x0024)}
        {"type":"list", "label":"operation", "default":3,  "list": ["A * B", "A / B", "A + B", "A - B"]}
        )
    if cancel: return

**Comment by plaresmedima** [comment]
@JSousa-UoL before I do this can you extend the doc string just a little bit?

- What does this function return?
- How do I specify defaults for the return values?
- Is it correct that there are 5 possible variable types (int, float, string, dropdownlist, listview)?
- Can I enter variables in the paramDict in any order I like? Do I just need to ensure that the order of the lists is the same? For instance can I enter a float, then a dropdownlist, then another float, then a listview, etc..

    def inputWindow(paramDict, title="Input Parameters", helpText="", lists=None):
        """
        Display a window and prompts the user to insert inputs. The input variables
        and respective types are defined in "paramDict". See below for examples.
        Variable "title" is the title of the window and "helpText" is the text
        displayed inside the window. It should be used to give important notes or 
        tips regarding the input process.

        Eg. of paramDict:
            paramDict = {"Tag":"string", "Value":"string"}
            The variable types are int, float and string.
            The user may add extra validation of the parameters. Read the file
            thresholdDICOM_Image.py as it contains a good example of validation.
        Other eg. of paramDict:
            inputDict = {"Algorithm":"dropdownlist", "Nature":"listview"}
            algorithmList = ["B0", "T2*", "T1 Molli"]
            natureList = ["Animals", "Plants", "Trees"]
            inputWindow(paramDict, ..., lists=[algorithmList, natureList])
        """

**Comment by JSousa-UoL** [comment]
I just made a commit with the docstring of this function re-written. It's quite long, but comprehensive and we can think of ways of shortening it in the future. But for now, this is what you'll need to know.

"""
    def inputWindow(paramDict, title="Input Parameters", helpText="", lists=None):
        Display a window and prompts the user to insert input values in the fields of the prompted window.
        The user has the option to choose what fields and variables are present in this input window.
        The input window variables and respective types are defined in "paramDict". See below for examples.
        Variable "title" is the title of the window and "helpText" is the text
        displayed inside the window. It should be used to give important notes or 
        tips regarding the input process.

        The user may add extra validation of the parameters. Read the file
        thresholdDICOM_Image.py as it contains a good example of validation of the input parameters.

        This function is a wrap of function "ParameterInputDialog" and you can consult it's detailed documentation
        in CoreModules/WEASEL/InputDialog.py.

        Parameters
        ----------
        paramDict: Dictionary containing the input variables. The key is the field/variable name and the value is the
                   type of the variable. There are 5 possible variable types - [int, float, string, dropdownlist, listview].
                   The dictionary doesn't have any limit of number of fields, the developer can insert as many as wished.
                   The order of the fields displayed in the window is the order set in the dictionary.
                   Eg. paramDict = {"NumberStaff":"int", "Password":"string", "Course":"dropdownlist"}.
                   "NumberStaff" comes first in the window and only accepts integers, then "Password" and then "Course", which is
                   a dropdown where the user can select an option from a set of options, which is given in the parameter "lists".
                   It's possible to assign default values to the input variables. Eg.paramDict = {"NumberStaff":"int,100"} sets the
                   variable "NumberStaff" value to 100.
                   
        title: String that contains the title of the input window that is prompted.

        helpText: String that contains any text that the developer finds useful. 
                  It's the introductory text that comes before the input fields.
                  This is a good variable to write instructions of what to do and how to fill in the fields.

        lists: If the values "dropdownlist" or/and "listview" are given in paramDict, then the developer provides the list of
               options to select in this parameter. This becomes a list of lists if there is more than one of "dropdownlist" or/and "listview".
               The order of the lists in this parameter should be respective to the order of the variables in paramDict. See examples below for
               more details.

        Output
        ------
        outputList: List with the values typed or selected by the user in the prompted window.
                    It returns "None" if the Cancel button or close window are pressed.
                    Eg: if param paramDict = {"Age":"int", "Name":"string"} and the user types 
                    "30" for Age and "Weasel" for Name, then the outputList will be [30, "Weasel"].
                    If "30" and "Weasel" are the default values, then paramDict = {"Age":"int,30", "Name":"string,Weasel"}

        Eg. of paramDict using string:
            paramDict = {"Threshold":"float,0.5", "Age":"int,30"}
            The variable types are float and int. "0.5" and "30" are the default values.

        Eg. of paramDict using string:
            paramDict = {"DicomTag":"string", "TagValue":"string"}
            This a good example where "helpText" can make a difference. 
            For eg., "DicomTag" should be written in the format (XXXX,YYYY).

        Eg. of paramDict using dropdownlist and listview:
            inputDict = {"Algorithm":"dropdownlist", "Nature":"listview"}
            algorithmList = ["B0", "T2*", "T1 Molli"]
            natureList = ["Animals", "Plants", "Trees"]
            inputWindow(paramDict, lists=[algorithmList, natureList])
"""

**Comment by plaresmedima** [comment]
Thanks. if the variable is dropdownlist or listview - does this return the
index of the selected item or the value? Can I set the defaults in the same
way?

  {"Algorithm":"dropdownlist, B0", "Nature":"listview, Plants"}

Prof. Steven Sourbron, PhD
Chair in Medical Imaging Physics
University of Sheffield, UK
*https
<https://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron>://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron
<https://www.sheffield.ac.uk/medicine/people/iicd/steven-sourbron>*
*Sheffield abdominal imaging research page*
<https://www.sheffield.ac.uk/medicine/research/research-themes/medical-imaging/medical-imaging-research/abdominal-imaging>
*Open source initiative in perfusion imaging* <http://www.osipi.org>
*Magnetic resonance imaging biomarkers for chronic kidney disease
<https://renalmri.org/>*

**Comment by JSousa-UoL** [comment]
For dropdownlist, assuming that B0 is the first element of your list, then it should be  {"Algorithm":"dropdownlist, 0"}. Note: I can't recall if the first element in this case is 0 or 1 because I tested it a long time ago, maybe @plaresmedima can advise on this.

For listview, I don't think we have a default approach from what I'm seeing in the code.

This information is all based on "CoreModules/WEASEL/InputDialog.py"

**Comment by plaresmedima** [comment]
@IMI-TRISTAN/Weasel ***@***.***> can you advise? Is the list
indexed at 0? Also, is there a space between the comma after the type and
the default value?

**Comment by plaresmedima** [comment]
@IMI-TRISTAN @JSousa-UoL 

I have committed the wrapper weasel.user_input(). See [Tutorial_UserInput.py](https://github.com/QIB-Sheffield/WEASEL/blob/master/Pipelines/Tutorial/Tutorial_UserInput.py) for an example of how this is used.

I also brought all three layers of the user_input() together in one class UserInput.py. It includes **inputWindow** from DeveloperTools and **inputDialog**. The originals have not yet been deleted.

UserInput.py is fully stand-alone - no dependencies with the rest of Weasel so can be run and tested on itself. 

**inputWindow** and **inputDialog** can still be retrieved from this and used as they were.

Instead of 

import CoreModules.WEASEL.InputDialog as inputDialog

now write

import CoreModules.UserInput as inputDialog

and inputWindow can be imported as follows:

from CoreModules.UserInput import inputWindow

So the file **inputDialog.py** can be deleted, and **inputWindow** can be deleted from DeveloperTools.

Please have a look..
