### ISSUE TITLE
Error renaming series in iBEAt_HarmonizedDataLeeds.py

### ISSUE THREAD

**Issue by plaresmedima** [QIB-Sheffield/WEASEL#87]
Line 21 in iBEAt_HarmonizedDataLeeds.py triggers this error:

Error in InterfaceDICOMXMLFile removeSeriesFromXMLFile: renameSeriesinXMLFile() 
missing 1 required positional argument: 'xmlSeriesName'

After completing the calculations, the series names on the treeview have not changed and asking for the MetaData gives an empty field and generates this error:

Error in : ViewMetaData.buildTableView'NoneType' object is not iterable
QLayout: Cannot add a null widget to QVBoxLayout/
Error in : ViewMetaData.buildTableView'NoneType' object is not iterable
QLayout: Cannot add a null widget to QVBoxLayout/

After reloading the DICOM data, the new sequences names are now shown and the metadata are visible

**Comment by JSousa-UoL** [comment]
@plaresmedima this should be resolved in the new commit. Please test and close as the code breaks on my side because of missing DICOM tags during anonymisation (I have old Leeds data that probably doesn't fit with the script).

**Comment by plaresmedima** [comment]
This seems to be working now so I am closing the issue
