### ISSUE TITLE
MultiFrame issues

### ISSUE THREAD

**Issue by plaresmedima** [QIB-Sheffield/WEASEL#89]
When data are loaded from multi-frame format, each series only shows a single image.

This needs to be handled differently. An image is by definition a 2D array. A series has multiple images, even if they are saved in the same file. The details of the fileformat should not affect what the user sees or how pipelines are written. We don't want to write every pipeline twice depending on which DICOM format the data happen to be saved in.

Solution 1: convert multiframe data into single frame data when opening the DICOM folder. Then within weasel handle single-frame data only.

Solution 2: leave as multiframe but handle this in the background. The treeview shows multiple images per series. If the user for instance checks a few images and does weasel.images().copy() - then a copy of the checked 2D images is saved as an extra frame in the same multi-frame file (i.e. same series).  

Proposal: move forward with solution 1 as this is easiest to implement. If needed multiframe support (solution 2) can be added later as this does not affect backwards compatibility.

![image](https://user-images.githubusercontent.com/6051075/110391260-253dfd00-805f-11eb-8b96-af19e372761a.png)

**Comment by JSousa-UoL** [comment]
Managed to implement Solution 1 in the most recent commit. 
The action was to add [dcm4che](https://github.com/dcm4che) which is a DICOM JAVA implementation. Command `emf2sf` reads Multiframe DICOM files and splits them in various Singleframe DICOM files. Weasel removes the original Multiframe DICOM file from the OS and loads the resulting Singleframe files

**Comment by JSousa-UoL** [comment]
**@plaresmedima commented:**

I try to Load MultiFrame data (001). I get these messages and then nothing happens.

Error in WriteXMLfromDICOM.get_scan_data: No DICOM files present in the selected folder
Error in function LoadDICOM.makeDICOM_XML_File: cannot unpack non-iterable NoneType object
Error in TreeView.makeDICOMStudiesTreeView at line 120: stat: path should be string, bytes, os.PathLike or integer, not NoneType

**Comment by JSousa-UoL** [comment]
I'd like to chat with you about the pros and risks in this Multiframe solution 1 and how we can do it better.

What probably happened (it happened to me during development) is that the `dcm4che` command didn't create the single frame files and then it deleted the original multiframe file. The result is that you end up with an empty folder and Weasel can't detect it afterwards. I recommend that you keep a copy of the multiframe data and check every know and then if the files are there.

**Comment by JSousa-UoL** [comment]
This should be solved now. The executables were never uploaded to Github in fact. [`emf2sf`](https://github.com/dcm4che/dcm4che/blob/master/dcm4che-tool/dcm4che-tool-emf2sf/README.md) was successfully added now.

**Comment by JSousa-UoL** [comment]
**@plaresmedima comment:**

Yes let's convert multi-frame to single-frame when the folder is first
opened, but let's do it in a copy of the folder so original data are not
deleted by default.

**Comment by JSousa-UoL** [comment]
Move "dcm4che-5.23.1" to External folder
