### ISSUE TITLE
bugs in merge series

### ISSUE THREAD

**Issue by plaresmedima** [QIB-Sheffield/WEASEL#97]
I try to merge the DTI series in iBEAt (series 31). I use Tutorial_MergeSeries.py. I get multiple error messages - see below. In the end a MergedSeries is generated and displayed but it contains non-DTI images of a series that I was not merging.

Error in function saveDICOM_Image.saveDicomToFile: [Errno 22] Invalid argument: 'C:\\Users\\steve\\Dropbox\\Data\\BEAt-DKD\\ssourbron-20210307_192732\\ssourbron-20210307_192732\\Leeds_Patient_4128005\\21\\DICOM\\1.3.12.2.1107.5.2.43.66097.30000019011510461753600000001-21-73-nhdpdc.dcm'
Error in WeaselXMLReader.removeOneImageFromSeries: [Errno 22] Invalid argument: 'C:/Users/steve/Dropbox/Data/BEAt-DKD/ssourbron-20210307_192732//ssourbron-20210307_192732.xml'
Error in WeaselXMLReader.removeOneImageFromSeries: [Errno 22] Invalid argument: 'C:/Users/steve/Dropbox/Data/BEAt-DKD/ssourbron-20210307_192732//ssourbron-20210307_192732.xml'
Error in WeaselXMLReader.removeOneImageFromSeries: [Errno 22] Invalid argument: 'C:/Users/steve/Dropbox/Data/BEAt-DKD/ssourbron-20210307_192732//ssourbron-20210307_192732.xml'
Error in WeaselXMLReader.removeOneImageFromSeries: [Errno 22] Invalid argument: 'C:/Users/steve/Dropbox/Data/BEAt-DKD/ssourbron-20210307_192732//ssourbron-20210307_192732.xml'
Error in WeaselXMLReader.removeOneImageFromSeries: [Errno 22] Invalid argument: 'C:/Users/steve/Dropbox/Data/BEAt-DKD/ssourbron-20210307_192732//ssourbron-20210307_192732.xml'
Error in WeaselXMLReader.removeOneImageFromSeries: [Errno 22] Invalid argument: 'C:/Users/steve/Dropbox/Data/BEAt-DKD/ssourbron-20210307_192732//ssourbron-20210307_192732.xml'
Error in : Weasel.hideProgressBar: 'Weasel' object has no attribute 'progBarMsg'
Error in : Weasel.closeMessageSubWindow: 'Weasel' object has no attribute 'msgSubWindow'

**Comment by JSousa-UoL** [comment]
This is an issue with the overwrite flag, it's not doing what it's meant to.
