### ISSUE TITLE
Loading MultiFrame data

### ISSUE THREAD

**Issue by plaresmedima** [QIB-Sheffield/WEASEL#98]
I try to Load MultiFrame data (001). I get these messages and then nothing happens.

Error in WriteXMLfromDICOM.get_scan_data: No DICOM files present in the selected folder
Error in function LoadDICOM.makeDICOM_XML_File: cannot unpack non-iterable NoneType object
Error in TreeView.makeDICOMStudiesTreeView at line 120: stat: path should be string, bytes, os.PathLike or integer, not NoneType

**Comment by JSousa-UoL** [comment]
I'm going to close this and copy this information to #89 as this is a strategy topic in my perspective.

I'd like to chat with you about the risks in this Multiframe approach. What probably happened (it happened to me during development) is that the dcm4che command didn't create the single frame files and then it deleted the original multiframe file. The result is that you end up with an empty folder. I recommend that you keep a copy of the multiframe data and check every know and then if the files are there
