### ISSUE TITLE
Two bugs in copy images

### ISSUE THREAD

**Issue by plaresmedima** [QIB-Sheffield/WEASEL#99]
I run Tutorial_CopyImages on series 1 (new data just reloaded). See screenshot 1. This should add another 12 images in the same series. Instead a new series is created at the bottom (screenshot 2). Moreover, this now is missing image and has an image 13 instead. If I try to delete the series, no error is generated but the series is not deleted.

![image](https://user-images.githubusercontent.com/6051075/111087160-e6ed8580-8517-11eb-80de-2100631872d1.png)

![image](https://user-images.githubusercontent.com/6051075/111087219-4c417680-8518-11eb-8a65-7c2c4efe243e.png)

**Comment by JSousa-UoL** [comment]
This was triggered by the change I did in the suffix request. I reverted it for now and confirmed that this was the cause. I'm trying to find viable solutions.
